Add previous visit finding functionality
ssec-jhu/biospecdb pull request #138
Opened 2023-10-16 21:28 UTC by vkluzner

2023-10-21 23:35 UTC, vkluzner commented on biospecdb/apps/uploader/models.py
> +            if last_visit != None:
> I'm curious, why didn't it work - what was the scenario for it to not work?

The condition `if self != last_visit `was satisfied, but without any reason, so logically it's wrong. I observed only two options:

- When it's first visit and then `previous_visit` is `None`

- When it's not a first visit and then `previous_visit` is not `None`

2023-10-21 23:38 UTC, vkluzner commented on biospecdb/apps/uploader/models.py
> +            if last_visit != None:
> _but_ it's def not ok for `previous_visit == self`.

Currently it never happens. At least, when I tested it extensively. I assume it may happen when we'll develop the code to update visits, but let's treat the cases once it's in development. Fow now there is no need for this comparison.

2023-10-23 00:03 UTC, vkluzner commented on biospecdb/apps/uploader/models.py
> +            if last_visit != None:
> > _but_ it's def not ok for `previous_visit == self`.
> 
> Currently it never happens. At least, when I tested it extensively. I assume it may happen when we'll develop the code to update visits, but let's treat the cases once it's in development. Fow now there is no need for this comparison.

Actually I found the case while developing the relevant pytest, so addd this condition to the code.

2023-10-23 22:20 UTC, jamienoss requested changes
There were a few things missing still, e.g., hoisting the code in clean to above the other ``previous_visit`` validators.

Given that this was to be the last review, I took a final and proper look and noticed that we need to auto find only when ``self.previsous_visit is None`` (for multiple reasons).

So instead of giving you more revision requests I just went ahead and made the changes for us in #148. Please review that and we can go from there, cheers.

2023-10-26 12:32 UTC, jamienoss approved these changes

2023-10-26 12:36 UTC, jamienoss commented on biospecdb/apps/uploader/views.py
> -                    try:
For the record 👀 these changes are causing the [codecov patch report](https://app.codecov.io/gh/ssec-jhu/biospecdb/pull/138?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=ssec-jhu) to fail.

2023-10-26 12:38 UTC, jamienoss commented
[codecov patch report](https://app.codecov.io/gh/ssec-jhu/biospecdb/pull/138?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=ssec-jhu) failing due to smuggled changes to ``view.py``.

2023-10-26 12:38 UTC, merged