Add prune_files management command to delete orphaned files
ssec-jhu/biospecdb pull request #220
Opened 2024-01-26 04:32 UTC by jamienoss

Resolves [Notion ticket](https://www.notion.so/Django-doesn-t-delete-files-on-disk-when-dereferenced-from-the-DB-e12623af4c8d471db8a39b6dceb3cfdb?pvs=4)

2024-01-26 04:34 UTC, jamienoss commented on README.md
> +Running ``python manage.py prune_files`` will delete all orphaned data files stored that have no associated database
Include ``--dry_run``

2024-01-27 11:26 UTC, glemson approved these changes
afaict code seems ok.
Will try locally.

2024-01-29 18:00 UTC, vkluzner requested changes

2024-01-29 18:30 UTC, jamienoss commented on biospecdb/apps/uploader/tests/test_management_commands.py
> +                              (("prune_files", "--dry_run"), (2, 10))))
These are tests and these values are specific to this test.

2024-01-29 18:31 UTC, vkluzner commented on biospecdb/apps/uploader/tests/test_management_commands.py
> +                              (("prune_files", "--dry_run"), (2, 10))))
ОК

2024-02-01 19:56 UTC, vkluzner approved these changes

2024-02-05 20:57 UTC, jamienoss commented
@amitschang Hey, just wondering if you planned to review this or whether I can merge?

2024-02-05 21:09 UTC, amitschang approved these changes
Some minor comments, OK either way so I will approve

2024-02-05 21:09 UTC, amitschang commented on biospecdb/apps/uploader/management/commands/prune_files.py
> +                    self.stdout.write(f"Deleting {msg}")
this might be better expressed with a log message prefix of "dry-run", same as the one below. The only difference being that you don't delete. Should compactify a bit as well

2024-02-05 21:09 UTC, amitschang commented on biospecdb/apps/uploader/management/commands/prune_files.py
> +                    os.remove(file)
technically, maybe it is ok if a `FileNotFound` error is raised here, we'd still be OK continuing since the end result is satisfied (this could happen if someone does this command concurrently?)

2024-02-05 21:32 UTC, amitschang approved these changes

2024-02-06 00:02 UTC, merged