Make Visit.patient_age -> Observable(category=PATIENT_INFO, name='patient_age')
ssec-jhu/biospecdb pull request #223
Opened 2024-01-27 21:50 UTC by jamienoss

Resolves [Notion ticket](https://www.notion.so/Make-patient_age-an-observable-67b934b46bad4bbaaa89fd848bd18bfd?pvs=4)

2024-01-27 22:53 UTC, jamienoss commented on biospecdb/apps/uploader/models.py
> -        if settings.AUTO_FIND_PREVIOUS_VISIT and (self.previous_visit is not None) and \
Slight smuggle (to avoid rebase conflict res). See https://github.com/ssec-jhu/biospecdb/pull/216/files#r1468672910

2024-01-27 22:53 UTC, jamienoss commented on biospecdb/apps/uploader/tests/test_models.py
> +                              pytest.param(marks=pytest.mark.auto_find_previous_visit(True))])
See https://github.com/ssec-jhu/biospecdb/pull/216/files#r1468672910

2024-01-28 13:29 UTC, glemson reviewed
two comments

2024-01-28 13:29 UTC, glemson commented on biospecdb/apps/uploader/models.py
> +                if self.days_observed > patient_age * 365:
this could cause problems.
say for an exactly 1 year old baby in a leap year.
or for a baby in its first few weeks or anywhere before turning 1.

How important is it to impose these validation restrictions anyway?

2024-01-28 13:29 UTC, glemson commented on biospecdb/apps/uploader/admin.py
> +            try:
what is this 'age' function used for?
Not for age at visit, for you have an observable for that.
nor for age sometime after the last visit for it would seem you cannot know the patient's age.

2024-01-28 14:52 UTC, jamienoss commented on biospecdb/apps/uploader/models.py
> +                if self.days_observed > patient_age * 365:
>How important is it to impose these validation restrictions anyway?

Not at all, I'll just remove it.

2024-01-28 14:55 UTC, jamienoss commented on biospecdb/apps/uploader/admin.py
> +            try:
Just the patient list display
<img width="1258" alt="Screenshot 2024-01-28 at 9 53 59 AM" src="https://github.com/ssec-jhu/biospecdb/assets/5013975/27e5d1c3-0273-486c-a7cc-d25658c576b0">

2024-01-28 15:12 UTC, jamienoss commented on biospecdb/apps/uploader/models.py
> +                if self.days_observed > patient_age * 365:
...or just make it conditional on ``age >=1``, I'm cool with either option. @glemson what's your pref?

2024-01-28 22:02 UTC, glemson commented on biospecdb/apps/uploader/admin.py
> +            try:
so this might not be accurate if the most recent visit was more than a year ago.

2024-01-28 22:03 UTC, glemson commented on biospecdb/apps/uploader/models.py
> +                if self.days_observed > patient_age * 365:
I would remove the constraint. if some child is being observed since after birth for multiple years it might not work for age 1 or 2  either.

2024-01-28 22:04 UTC, glemson requested changes
I suggest removing the constraint that age*365 should be >= days observed

2024-01-28 22:15 UTC, jamienoss commented on biospecdb/apps/uploader/admin.py
> +            try:
Correct. I think that should be ok though, no?

2024-01-28 22:35 UTC, glemson approved these changes
ok.

2024-01-28 22:35 UTC, glemson commented on biospecdb/apps/uploader/admin.py
> +            try:
ok.

2024-01-29 18:26 UTC, vkluzner approved these changes

2024-01-29 18:28 UTC, merged